### PR TITLE
Fix description of INTO

### PR DESCRIPTION
**Pull request by gahr**

### CODE REVIEW

**Comment by gahr** [comment]
I’ll open a similar PR to fix the same comme t in classes.lisp if this is accepted.

**Comment by stylewarning** [comment]
> I’ll open a similar PR to fix the same comme t in classes.lisp if this is accepted.

If you fix classes.lisp, the merge will auto-generate and fix the documentation.

**Comment by stylewarning** [comment]
(The fix is welcome! But the correct place to fix is indeed classes.lisp.)

**Comment by gahr** [comment]
Ah! I knew you guys wouldn't write the same thing in two places :) Thanks!

**Pull request closed without merging**
